### ISSUE TITLE
future request for a beautiful card design

### ISSUE THREAD

**Issue by proXDhiya** [SabineBen/Debit_Card#1]
I have a future request for you 

- [ ] add this line to your **CSS** code --  inside `.card` selector

```css
.card {
        backdrop-filter: blur(2px);
}
```
you will get a nice glass effect on your card 🥰
